// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkgdmftogjpaiqusjivw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrZ2RtZnRvZ2pwYWlxdXNqaXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDczMzgsImV4cCI6MjA2MDE4MzMzOH0.T9OTZy_kOZ5mHECV0szvfjFiegoSJnAO_3hLdhsz1JI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);